#pragma once

#include "Tactility/i18n/TextResources.h"

// WARNING: This file is auto-generated. Do not edit manually.

namespace tt::app::contacts::i18n {

enum class Text {
    APP_NAME = 0,
    REFRESH = 1,
    WAITING_FOR_EVENTS = 2,
    MANUAL_REFRESH = 3,
    SUBSCRIBED = 4,
    RETICULUM_UPDATED = 5,
    SUMMARY_FMT = 6,
    NO_CONTACTS_OBSERVED = 7,
    NO_ADDITIONAL_DETAIL = 8,
    LOCAL_DESTINATION = 9,
    PROVISIONAL_LOCAL_DESTINATION = 10,
    ACCEPTS_LINKS = 11,
    NO_LINKS = 12,
    LOCAL_SUBTITLE_FMT = 13,
    INTERFACE_UNKNOWN = 14,
    INTERFACE_KIND_UNKNOWN = 15,
    VIA_INTERFACE_FMT = 16,
    PATH_RESPONSE_ANNOUNCE_FMT = 17,
    ANNOUNCE_OBSERVED_FMT = 18,
    PATH_LEARNED = 19,
    PATH_VIA_FMT = 20,
    UNRESPONSIVE_SUFFIX = 21,
    REACHABLE_FMT = 22,
    CONTACT_LINE_FMT = 23,
    RUNTIME_STARTING = 24,
    RUNTIME_READY = 25,
    RUNTIME_STOPPING = 26,
    RUNTIME_STOPPED = 27,
    RUNTIME_FAULTED = 28,
    EVENT_RUNTIME_STATE_CHANGED_FMT = 29,
    EVENT_INTERFACE_ATTACHED = 30,
    EVENT_INTERFACE_DETACHED = 31,
    EVENT_INTERFACE_STARTED = 32,
    EVENT_INTERFACE_STOPPED = 33,
    EVENT_LOCAL_DESTINATION_REGISTERED = 34,
    EVENT_ANNOUNCE_OBSERVED = 35,
    EVENT_PATH_TABLE_CHANGED = 36,
    EVENT_ERROR = 37,
};

}
